### PR TITLE
periodically refresh dns name

### PR DESCRIPTION
**Pull request by jjofseattle**
First I reformat the files from ts=2 to ts=4.  Please add `?w=1` when you review the diffs.

In k8s sometimes we move the statsd instances, `statsd.production` could point to different addresses at different time.  Since we had cacheDns set to true, currently we have to bounce the services to pick up the new addresses.

This is to fix the problem.  At the same interval we refresh the socket, I added code to refresh dns record too.  Some the metrics will be lost for at most a minute(the default interval).

This doesn't address the service restarts caused by dns failure.  I will have a different pr in hurley-metrics to fix that.

### CODE REVIEW

**Comment by rrusso1982** [comment]
The dns address of statsd should not be changing as it runs as a service within kubernetes.  The item that is changing under the hood is the address of the statsd-proxy that your udp connection is emitting metrics to.  This change is handled at the iptables nat level.  As far as your service knows the address of statsd has not changed.  I'm not sure you are going to get the results from this that you are expecting.

**Comment by jjofseattle** [comment]
@rrusso1982 I am not aware of that.  For what you just said, why bouncing the services fixes the problem?

**Comment by rrusso1982** [comment]
Because bouncing the service recreates the stale UDP socket that the client is still using to send metrics.  The UDP socket is using a CONNTRACK entry that has not been released because the socket still exists.  Once the UDP socket is rebuilt it gets the new nat update from iptables.

**Comment by jjofseattle** [comment]
@rrusso1982 could you explain more?  It could be deeper than that.

For example, we already has code to recreate the socket every minute, mostly likely to handle the above mentioned situation.  But apparently it didn't work?

https://github.com/HBOCodeLabs/node-statsd/blob/master/lib/statsd.js#L273

**Comment by rrusso1982** [comment]
@Jonnymcc I think it's best if you chime in on this since you did the initial research on the UDP socket problems.

**Comment by jjofseattle** [comment]
@rrusso1982 @Jonnymcc even this may not fix the socket problem, it could still help when the dns resolution fails at the beginning.

**Comment by Jonnymcc** [comment]
I'll have to create a video of me testing this in minikube since it is fairly complicated to test... but recreating the UDP socket is sufficient to begin sending traffic to a new endpoint, re-resolving the DNS name is unnecessary. (In my testing, re-resolving the DNS name will actually flood the conntrack tables, not sure if there is a performance impact though...) And in Kuberentes 1.6.(?) this is UDP issue is fixed and then recreating the UDP socket also becomes unnecessary.

**Comment by Jonnymcc** [comment]
@jjofseattle r.e. the failure to resolve DNS, I think that is a problem to be solved at the DNS layer. kube-dns has been performing poorly and still either needs more tuning or should be replaced with something else.

**Comment by Jonnymcc** [comment]
As for "Why does bouncing the service fix the problem?" It is because when you "bounce" the pod, you are terminating the old one and recreating a new one (I believe), and because there is a new pod created with a new source port there is no existing NAT rule in conntrack, which means a new one gets created when the UDP socket first connects to the statsd endpoint.

**Comment by jjofseattle** [comment]
okay, understood now.  I will close this one.

**Pull request closed without merging**
